version: '3.8'
services:
  postgresdb:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - kafka_es_ms_network

#  mysqldb:
#    image: mysql:8.2
#    container_name: mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'ecommerce'
#      MYSQL_USER: 'mysql'
#      MYSQL_PASSWORD: 'mysql123'
#      MYSQL_ROOT_PASSWORD: 'mysql123'
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    volumes:
#      - mysql_db:/var/lib/mysql
#    ports:
#      - '3307:3306'
#    networks:
#      - kafka_es_ms_network

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: mongo123
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - kafka_es_ms_network

  product-service:
    build:
      dockerfile: Dockerfile
      context: ./product-service
    ports:
      - 8001:8001
    depends_on:
      - postgresdb
    environment:
      DB_PASSWORD: postgres123
      NODE_ENV: development
      CLOUD_ID: 4748882a49494f44b9d08c3cb8cf8222:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDg4MzBiYzlmMGY1YTRhZjhiOTBkNTg3MzBhZGQ2NzNmJGZhMmVmMDk4YjRkNTQzODE5NzcxNzQ4ZjI5ODNlZTEw
      ELASTIC_PASSWORD: Jesusislordforever7+
    networks:
      - kafka_es_ms_network

  order-service:
    build:
      dockerfile: Dockerfile
      context: ./order-service
    ports:
      - 8002:8002
#    depends_on:
#      - mysqldb
    environment:
      - db_password=Jesusislordforever7+
      - NODE_ENV=development
      - cloud_id=4748882a49494f44b9d08c3cb8cf8222:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDg4MzBiYzlmMGY1YTRhZjhiOTBkNTg3MzBhZGQ2NzNmJGZhMmVmMDk4YjRkNTQzODE5NzcxNzQ4ZjI5ODNlZTEw
      - elastic_password=Jesusislordforever7+
    networks:
      - kafka_es_ms_network

  payment-service:
    build:
      dockerfile: Dockerfile
      context: ./payment-service
    ports:
      - 8003:8003
    depends_on:
      - mongodb
    environment:
      DB_PASSWORD: mongo123
      NODE_ENV: development
    networks:
      - kafka_es_ms_network

  api-gateway:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    ports:
      - 8000:80
    depends_on:
      - product-service
      - order-service
      - payment-service
    networks:
      - kafka_es_ms_network

networks:
  kafka_es_ms_network:

volumes:
  postgres_db:
  mysql_db:
  mongo-data: