version: '3.8'
services:
  postgresdb:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - kafka_es_ms_network

  mysqldb:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql123
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - kafka_es_ms_network

  mongodb:
    image: mongo
    container_name: mongo
      restart: always
      environment:
        MONGO_USER: mongo
        MONGO_PASSWORD: mongo123
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - kafka_es_ms_network

  product-service:
    build:
      dockerfile: Dockerfile
      context: ./product-service
    ports:
      - 8001:8001
    depends_on:
      - postgresdb
    environment:
      DB_PASSWORD: postgres123
      NODE_ENV: development
    networks:
      - kafka_es_ms_network

  order-service:
    build:
      dockerfile: Dockerfile
      context: ./order-service
    ports:
      - 8002:8002
    depends_on:
      - mysqldb
    environment:
      DB_PASSWORD: mysql123
      NODE_ENV: development
      API_KEY: S3N3cU5ZOEJYWHFUN2RPQVZacF86YXl1M2NuSjNSNGE2bHZGSHFiR2h1Zw
    networks:
      - kafka_es_ms_network

  payment-service:
    build:
      dockerfile: Dockerfile
      context: ./payment-service
    ports:
      - 8003:8003
    depends_on:
      - mongodb
    environment:
      DB_PASSWORD: mongo123
      NODE_ENV: development
    networks:
      - kafka_es_ms_network

  api-gateway:
    build:
      dockerfile: Dockerfile
      context: ./nginx-api-gateway
    ports:
      - 8000:80
    depends_on:
      - product-service
      - order-service
      - payment-service
    networks:
      - kafka_es_ms_network

networks:
  kafka_es_ms_network:

volumes:
  postgres_db:
  mysql_db: