version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - kafka_es_ms_network
    volumes:
      - ./db/mysql-data:/var/lib/mysql

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - kafka_es_ms_network
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - 27010:27017
    volumes:
      - ./db/mongodb_data:/data/db
      - ./payment-service/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - kafka_es_ms_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - kafka_es_ms_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_es_ms_network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8001:8001'
    depends_on:
      - postgresdb
    environment:
      - NODE_ENV=${NODE_ENV}
      - db_password=${POSTGRES_PASSWORD}
      - cloud_id=${CLOUD_ID}
      - elastic_password=${ELASTIC_PASWORD}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - kafka_es_ms_network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8002:8002'
    depends_on:
      - mysqldb
      - kafka
    environment:
      - db_password=${MYSQL_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - cloud_id=${CLOUD_ID}
      - elastic_password=${ELASTIC_PASSWORD}
    networks:
      - kafka_es_ms_network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8003:8003'
    environment:
      - db_password=${MONGO_DB_PASSWORD}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb
      - kafka
    networks:
      - kafka_es_ms_network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - product-service
      - order-service
      - payment-service
    networks:
      - kafka_es_ms_network

networks:
  kafka_es_ms_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  mongo-data:
    driver: local
  mysql-data:
    driver: local